#DO NOT PUT YOUR KEYS IN THIS FILE, FOR EXAMPLE ONLY
#MAKE A COPY NAMED 'keys.py' and place your keys in that

#twitter auth
CONSUMER_KEY = ""
CONSUMER_SECRET = ""
ACCESS_TOKEN = ""
ACCESS_TOKEN_SECRET = ""
